# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: 'b3f0b500-1750-44d7-948f-15705ba7c816'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'charlesproject1'
    location: 'Central US'
    templateLocation: 'Linked artifact'
    csmFile: 'CreateStorageAccount/azuredeploy.json'
    overrideParameters: '-projectName AzureRmPipeline -linkedTemplateUri https://github.com/agbate/AzureRmPipeline-repo/blob/master/CreateStorageAccount/linkedStorageAccount.json'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
